sudo: required
dist: trusty
language: node_js
node_js:
  - node

services:
  - postgresql

before_script:
  - npm install
  - psql -c 'create database doc_manager_test;' -U postgres
  - dropdb --if-exists doc_manager_test && createdb doc_manager_test
  - NODE_ENV=test npm run db:migrate:test
  - npm run coveralls

after_success:
- npm run coveralls

after_failure:
- npm run coveralls
